### ISSUE TITLE
Another NULL dereference in ippWriteIO/strlen attribute name

### ISSUE THREAD

**Issue by catenacyber** [OpenPrinting/cups#196]
Found by fuzzing
Getting the crash with `./fuzzipp crash-bb782a5d8b65fa64c969afbe0c556bc744193660
with crash-bb782a5d8b65fa64c969afbe0c556bc744193660 being a file whose base64 encoding is
```
AgAAAgAAAAEBRwASYXR0cmlidXRlcy1jaGFyc2V0AAV1dGYtOEgAG2F0dHJpYnV0ZXMtbmF0dXJh
bC1sYW5ndWFnZQAFZW4tdXNFAAtwcmludGVyLXVyaQAcaXBwOi8vbG9jYWxob3N0L3ByaW50ZXJz
L2Zvb0IAFHJlcXVlc3RpbmctdXNlci1uYW1lAAhqb2huLWRvZUIACGpvYi1uYW1lAAhUZXN0IEpv
YgJEABBwcmludC1jb2xvci1tb2RlAAVjb2xvciMADXByaW50LXF1YWxpdHkABAAAAAUhAAZjb3Bp
ZXMABAAAACozAAtwYWdlLXJhbmdlcwAIAHEAAQAAADIxABNqb2ItaG9sZC11bnRpbC10aW1lAAsH
5QYHDxkYACsAAEEAF2pvYi1tZXNzYWdlLXRvLW9wZXJhdG9yABNUaGlzIGlzIGEgdGVzdCBqb2Iu
NAAJbWVkaWEtY29sAABKAAAACm1lZGlhLXNpemU0AAAAAEoAAAALeC1kaW1lbnNpb24hAAAABAAA
VFZKAAAAC3ktZGltZW5zaW9uIQAAAAQAAG0kNwAAAABKAABtJDcAAAAASmNvbG9yRAAAAARibHVl
SgAAAAptZWRpYS10eXBlRAABAApzdGF0aW9uZXJ5NwAAAAAD
```

Stack trace is
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2889==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7feae61137c6 bp 0x7ffd933a0090 sp 0x7ffd9339f848 T0)
==2889==The signal is caused by a READ memory access.
==2889==Hint: address points to the zero page.
    #0 0x7feae61137c6 in strlen (/lib/x86_64-linux-gnu/libc.so.6+0x8b7c6)
    #1 0x55f1548c85f8 in strlen /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc
    #2 0x55f15499af73 in ippWriteIO /src/cups/cups/ipp.c:5475:27
    #3 0x55f15499b6d0 in ippWriteIO /src/cups/cups/ipp.c:6032:9
    #4 0x55f154962714 in main /src/cups/cups/fuzzipp.c:198:15
```

**Comment by michaelrsweet** [comment]
OK, so confirmed this but it is another crash that can't happen in real life since cupsd, ippserver, etc. would not use an IPP message that failed to load/read.

**Comment by michaelrsweet** [comment]
[ipptool 7c365a394] Further harden ippReadIO to prevent invalid IPP message data from being preserved (Issue #196)

The latest changes introduce a "rollback" target that deletes the most recently added attribute when a read error occurs. This should prevent any invalid IPP data from being propagated to ippWriteIO, even accidentally.

**Comment by catenacyber** [comment]
Thanks Michael, running https://github.com/google/oss-fuzz/pull/5885 may find similar crashes...
