### ISSUE TITLE
Core Dumped After each print job

### ISSUE THREAD

**Issue by almanfu** [OpenPrinting/cups#328]
OS: Ubuntu 20.04 LTS
Ver.: CUPS 2.3.1
Printer and drivers: Samsung M2070 Series, driverless, cups-filters 1.27.4
After each job, which is succesfully finished (the printer DOES print), cups crashes and takes 3 minutes to get back online, here the status report: 
```
● cups.service - CUPS Scheduler
     Loaded: loaded (/lib/systemd/system/cups.service; enabled; vendor preset: enabled)
     Active: deactivating (stop-sigterm) (Result: core-dump) since Wed 2022-01-26 10:52:35 CET; 2s ago
TriggeredBy: ● cups.path
             ● cups.socket
       Docs: man:cupsd(8)
    Process: 24864 ExecStart=/usr/sbin/cupsd -l (code=dumped, signal=ABRT)
   Main PID: 24864 (code=dumped, signal=ABRT)
      Tasks: 1 (limit: 18837)
     Memory: 3.3M
     CGroup: /system.slice/cups.service
             └─24949 implicitclass://Samsung_M2070_Series_SEC30CDA71ABF6A_/ 9 manfucci Twitter.png.pdf 1 MediaType=Stationery number-up=1 >

gen 26 10:51:58 manfucci-Inspiron-7501 systemd[1]: Started CUPS Scheduler.
gen 26 10:52:35 manfucci-Inspiron-7501 cupsd[24864]: free(): invalid pointer
gen 26 10:52:35 manfucci-Inspiron-7501 systemd[1]: cups.service: Main process exited, code=dumped, status=6/ABRT
```
Someone is freeing an invalid pointer

**Comment by zdohnal** [comment]
Hi @almanfu ,

cups-2.3.1 is several years old, the current CUPS version is 2.4.1 - it would be great if you reported the issue to your OS maintainers.

I can only check whether the current code is affected as well, but I would need a backtrace from the crash - would you mind providing it?

Thank you in advance!

**Comment by almanfu** [comment]
Thanks for your quick reply. Will probably install the newest version. Here is the backtrace.
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f7241694859 in __GI_abort () at abort.c:79
#2  0x00007f72416ff3ee in __libc_message (action=action@entry=do_abort, 
    fmt=fmt@entry=0x7f7241829285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f724170747c in malloc_printerr (
    str=str@entry=0x7f72418274ae "free(): invalid pointer") at malloc.c:5347
#4  0x00007f7241708cac in _int_free (av=<optimized out>, p=<optimized out>, 
    have_lock=0) at malloc.c:4173
#5  0x00007f724189b1de in ?? () from /lib/x86_64-linux-gnu/libcups.so.2
#6  0x00007f724189b143 in ippDelete () from /lib/x86_64-linux-gnu/libcups.so.2
#7  0x000055bb1c57c7ac in ?? ()
#8  0x000055bb1c5b6b98 in ?? ()
#9  0x000055bb1c573b74 in ?? ()
#10 0x00007f72416960b3 in __libc_start_main (main=0x55bb1c573220, argc=2, 
    argv=0x7fff7ce38148, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fff7ce38138)
    at ../csu/libc-start.c:308
#11 0x000055bb1c574eee in ?? ()
```

**Comment by zdohnal** [comment]
@almanfu please install the debuginfo packages and get the backtrace once again - the current has many undefined stuff.

Thank you in advance!

**Comment by zdohnal** [comment]
No response for a month, closing the issue.
